name: get model training status

on:
  workflow_dispatch:
  push:
    branches: [ scenera-devcontainer ]
  # schedule:
  #   - cron: '*/5 * * * *' # every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run train_model_status.py
        run: |
            import os
            print(os.environ['PATH'])
            print %ENV
            python train_model_status.py