name: train custom model

on:
  workflow_dispatch:
    inputs:
      datasetName: 
        description: 'Name of dataset in Azure Custom Vision'     
        required: true
        default: 'sceneradatasetv1'
        type: string
      modelName: 
        description: 'Name of the custom model to train in Azure Custom Vision'     
        required: true
        default: 'scenera-model-v1'
        type: string
      resourceName: 
        description: 'Name of the computer vision resource in Azure'     
        required: true
        default: 'scenera-computervision-rnd-resource'
        type: string
jobs:
  train-custom-model:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: train custom model
        env:
          RESOURCE_KEY: ${{secrets.RESOURCE_KEY}} 
          INPUT_MODEL_NAME: ${{ github.event.inputs.modelName }}
          INPUT_DATASET_NAME: ${{ github.event.inputs.datasetName }} 
          INPUT_RESOURCE_NAME: ${{ github.event.inputs.resourceName }}
        run: python train.py
        shell: bash
        id: training
        working-directory: ./src/model
      - run: |
          echo "-> ${{ steps.training.outputs.myoutput }}" 
          echo "mynew_output=${{ steps.training.outputs.myoutput }}" >> "$GITHUB_ENV" 
  get_model_training_status:
    needs: train-custom-model
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: install python packages
        run: |
          echo "****************************"
          echo "-----------> $mynew_output"  
          printf '%s\n' "$mynew_output" 
          echo "****************************"
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: get training model status
        env:
          RESOURCE_KEY: ${{secrets.RESOURCE_KEY}}
          INPUT_MODEL_NAME: ${{ github.event.inputs.modelName }}
          INPUT_DATASET_NAME: ${{ github.event.inputs.datasetName }} 
          INPUT_RESOURCE_NAME: ${{ github.event.inputs.resourceName }}  
        run: |
          python model_status.py
        working-directory: ./train_custom_model

  # log_training_metrics:
  #   needs: get_model_training_status
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: checkout repo content
  #       uses: actions/checkout@v2

  #     - name: setup python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.10' 
  #     - name: install python packages
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install -r requirements.txt

  #     - name: log training metrics
  #       env:
  #         RESOURCE_KEY: ${{secrets.RESOURCE_KEY}}
  #         INPUT_MODEL_NAME: ${{ github.event.inputs.modelName }}
  #         INPUT_DATASET_NAME: ${{ github.event.inputs.datasetName }} 
  #         INPUT_RESOURCE_NAME: ${{ github.event.inputs.resourceName }}  
  #       run: |
  #         python log_model_metrics.py
  #       working-directory: ./train_custom_model
