name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  train-dev:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: run training job
      run: az ml job create --file job.yml --resource-group scenera-demo --workspace-name scenera-demo-ml --stream
      working-directory: src/
  train-prod:
    needs: train-dev
    runs-on: ubuntu-latest
    environment: production
    outputs:
      runId: ${{ steps.prod-job-step.outputs.runId }}
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}  
    - name: run prod job
      id: prod-job-step
      run: |
        runId=$(az ml job create --file prod-job.yml --resource-group scenera-demo --workspace-name scenera-demo-ml --stream | grep RunId)
        runId_value=${runId#* }
        echo "this is the runID: $runId_value"
        echo "runId='$runId_value'" >> "$GITHUB_OUTPUT"
      working-directory: src/      
  job3:
    runs-on: ubuntu-latest
    needs: train-prod
    steps:
      - env:
          RUNID: ${{needs.train-prod.outputs.runId}}
        run: echo "$RUNID"
