name: train custom model

on:
  workflow_dispatch:
    inputs:
      site_name:
        description: 'Name of dataset in Azure Custom Vision'  
        required: true
        default: 'sample-dataset'
        type: string

jobs:
  train-custom-model:
    runs-on: ubuntu-latest
    outputs:
      model_name: ${{ steps.step1.outputs.model_name }}
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: train custom model
        id: step1
        env:
          RESOURCE_KEY: ${{secrets.RESOURCE_KEY}}  
        run: |
          echo "Model Name: ${{ github.event.inputs.myInput }}"
          model_name=${{ github.event.inputs.myInput }}
          echo "Output [$model_name]"
          echo "model_name=$model_name" >> $GITHUB_OUTPUT
          INPUT_MODEL_NAME=${{ github.event.inputs.myInput }} python train_model_v2.py
        working-directory: ./train_custom_model
  get_model_training_status:
    needs: train-custom-model
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: get training model status
        env:
          MODEL_NAME: ${{needs.job1.outputs.output1}}
          RESOURCE_KEY: ${{secrets.RESOURCE_KEY}}  
        run: |
          echo model_name [${{needs.step1.outputs.model_name}}]
          python model_status.py
        working-directory: ./train_custom_model

  log_training_metrics:
    needs: get_model_training_status
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: log training metrics
        env:
          RESOURCE_KEY: ${{secrets.RESOURCE_KEY}}  
        run: |
          python log_model_metrics.py
        working-directory: ./train_custom_model
